// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lothar1998/v2x-optimizer/internal/performance/optimizer (interfaces: PerformanceOptimizer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/lothar1998/v2x-optimizer/pkg/data"
	optimizer "github.com/lothar1998/v2x-optimizer/pkg/optimizer"
)

// MockPerformanceOptimizer is a mock of PerformanceOptimizer interface.
type MockPerformanceOptimizer struct {
	ctrl     *gomock.Controller
	recorder *MockPerformanceOptimizerMockRecorder
}

// MockPerformanceOptimizerMockRecorder is the mock recorder for MockPerformanceOptimizer.
type MockPerformanceOptimizerMockRecorder struct {
	mock *MockPerformanceOptimizer
}

// NewMockPerformanceOptimizer creates a new mock instance.
func NewMockPerformanceOptimizer(ctrl *gomock.Controller) *MockPerformanceOptimizer {
	mock := &MockPerformanceOptimizer{ctrl: ctrl}
	mock.recorder = &MockPerformanceOptimizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPerformanceOptimizer) EXPECT() *MockPerformanceOptimizerMockRecorder {
	return m.recorder
}

// CacheEligible mocks base method.
func (m *MockPerformanceOptimizer) CacheEligible() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheEligible")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CacheEligible indicates an expected call of CacheEligible.
func (mr *MockPerformanceOptimizerMockRecorder) CacheEligible() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheEligible", reflect.TypeOf((*MockPerformanceOptimizer)(nil).CacheEligible))
}

// Identifier mocks base method.
func (m *MockPerformanceOptimizer) Identifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// Identifier indicates an expected call of Identifier.
func (mr *MockPerformanceOptimizerMockRecorder) Identifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identifier", reflect.TypeOf((*MockPerformanceOptimizer)(nil).Identifier))
}

// Optimize mocks base method.
func (m *MockPerformanceOptimizer) Optimize(arg0 context.Context, arg1 *data.Data) (*optimizer.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Optimize", arg0, arg1)
	ret0, _ := ret[0].(*optimizer.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Optimize indicates an expected call of Optimize.
func (mr *MockPerformanceOptimizerMockRecorder) Optimize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Optimize", reflect.TypeOf((*MockPerformanceOptimizer)(nil).Optimize), arg0, arg1)
}
