// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lothar1998/v2x-optimizer/internal/performance/optimizer (interfaces: PerformanceSubjectOptimizer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/lothar1998/v2x-optimizer/pkg/data"
	optimizer "github.com/lothar1998/v2x-optimizer/pkg/optimizer"
)

// MockPerformanceSubjectOptimizer is a mock of PerformanceSubjectOptimizer interface.
type MockPerformanceSubjectOptimizer struct {
	ctrl     *gomock.Controller
	recorder *MockPerformanceSubjectOptimizerMockRecorder
}

// MockPerformanceSubjectOptimizerMockRecorder is the mock recorder for MockPerformanceSubjectOptimizer.
type MockPerformanceSubjectOptimizerMockRecorder struct {
	mock *MockPerformanceSubjectOptimizer
}

// NewMockPerformanceSubjectOptimizer creates a new mock instance.
func NewMockPerformanceSubjectOptimizer(ctrl *gomock.Controller) *MockPerformanceSubjectOptimizer {
	mock := &MockPerformanceSubjectOptimizer{ctrl: ctrl}
	mock.recorder = &MockPerformanceSubjectOptimizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPerformanceSubjectOptimizer) EXPECT() *MockPerformanceSubjectOptimizerMockRecorder {
	return m.recorder
}

// CacheEligible mocks base method.
func (m *MockPerformanceSubjectOptimizer) CacheEligible() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheEligible")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CacheEligible indicates an expected call of CacheEligible.
func (mr *MockPerformanceSubjectOptimizerMockRecorder) CacheEligible() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheEligible", reflect.TypeOf((*MockPerformanceSubjectOptimizer)(nil).CacheEligible))
}

// Identifier mocks base method.
func (m *MockPerformanceSubjectOptimizer) Identifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// Identifier indicates an expected call of Identifier.
func (mr *MockPerformanceSubjectOptimizerMockRecorder) Identifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identifier", reflect.TypeOf((*MockPerformanceSubjectOptimizer)(nil).Identifier))
}

// Optimize mocks base method.
func (m *MockPerformanceSubjectOptimizer) Optimize(arg0 context.Context, arg1 *data.Data) (*optimizer.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Optimize", arg0, arg1)
	ret0, _ := ret[0].(*optimizer.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Optimize indicates an expected call of Optimize.
func (mr *MockPerformanceSubjectOptimizerMockRecorder) Optimize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Optimize", reflect.TypeOf((*MockPerformanceSubjectOptimizer)(nil).Optimize), arg0, arg1)
}
