name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42

      - name: Test
        run: make test

      - name: Build
        run: make build
