name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Linter
        run: go get -u golang.org/x/lint/golint

      - name: Info
        run: make info

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test